language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: dKmV+izdw9BbqOd8FKQF04SZMgf2/cLKulhkpwQp7BsLj7tRI9pDViw0Za9rI/myE566m+ql7eG+N2/PKuSc5F2UowcYB1gg+A/f3dUOWGxPqzhSWwng5a/nMXy+bwS5g8M8d3t17ur3L1xFF7mZ/EKD4SetcY96bIY4OYNHcVrWhoYqO4XTMHVw3AG5k8y2PAdFc/NTgQqdMgp1WXwgxaBD8zHtJBYQf8kj/7+iTuGcfZNOM/2QhpQ1jH0jcL4CyWiUsYZKQo8SwXemiWFpOzv8Mqkla6X13npZZ7ey4udxPKC16BrIvb0oqDDAJpZ1EoUe/9CDrTO4nPwIvHZ5zOeSgdMolXgamx+t4q1CgVTkIYs+ra64+gKNNftep+/Slpn1A6G7kaEZFU/pUEeQrihtADoUMBfFBzNHoO6xC0SQUU8MPVt/7ghDP1HzzKNvcvHtj8dXR1bMESst/TbY0KRH+pE1eWbeQ7hMngs9BDp6PAAlgHemh+b9ouTivvwXTTNZ4YpUxAiu0JKUY+etf4u7fh/xXcdlzBSrY9kHEws+1/3k+3ZcXP/hs+nhwclNnIGjLsPogyD4/4LaBl4WIMAl61jtJQnIE1qvkWUBo5sUtQ3iXvGpUPFGrLq44RPMyvqqL4FpQ1U55I0lVM4jJJyH32/YRBsOOmvug0Jdngo=
  - secure: UxnUCETTXIaSSFhOtyvCvEiIEh0gpf/qOmLf9QsdHfEUaUyJrnzHXS462ggbRQoNBa8FSOD7dc/oh1EZKUW5dT2BSGSlzi4L98/SH1xRlfbz6xy0GORWuqNeceZ3IXnPOKuGAtIOaXeUtCHWej5gHukfdigVR1QxEizfxnGQU+ONwTMZ3W/0HERjGmaYB1bsKcLWb1tJna8mH/btZJpgaArH1VwfWoJ147jwpgqGDEqoLgMl/r+ABvU5WSlXPANwPU5qt0jJR3QN5gjQ/Jd80Ful6HKqkGk1N10fr6X34j28cLPilT3pCsxa+/2pkDaJGETNqWMSBXIUht3TJS5IfH6DgOlLoMIXJgn/av4b20g9Zwl0Q8Q0IpJmNwOEcM/D7wZhtjIzQMH+XVmFpYxPXJJZGogkvdveTDoVvsJbW31nA16RjUHjl/JTAVZZr6Yj9u0jDa6ndJuSIKqMFiyexXI+TEGUprGkWPzDXhQuKqyQQG2q7SAbDeeDKUwgCcJ/JpCccBUfRITd+JWUdaQs9Vtc3OXZyvvEbMfh/iqX6WI3OUYQSYuENTpNSJBK8ceVHP28M/XaaJNk+R3INLjldR0EJsthwNc0LRYVNYJFdBiFOtnRFPlfoJokQ0RtaMYrnS8HgxYB3sxjvsElhjxnsplj/ynrIbmxtQvyOZ3w+3U=
