/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   client-certificates-panel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {ClientCertificatesPanel} from './src/ClientCertificatesPanel.js';
